### ISSUE TITLE
Salt doesn't accept Microsoft-Key for Visual Studio Code on openSUSE

### ISSUE THREAD

**Issue by Maini12** [openSUSE/zypper#200]
We want to setup openSUSE in our Linux laboratory at TH Nuernberg.
That should be done automatically with Salt installing Visual Studio Code.
Steps to reproduce:
1. vscode.sls inside salt-Directory:
```
vscode:
  pkgrepo.managed:
    - humanname: "Microsoft Visual Studio Code"
    - mirrorlist: https://packages.microsoft.com/yumrepos/vscode
    - gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    - gpgcheck: 1
    - enabled: 1
    - type: rpm-md
  pkg.installed:
    - name: code
    - fromrepo: vscode
```
2. Deploy with _salt '*' state.apply vscode_

3. Exceptions:
-    /var/log/zypper.log:

> 2018-08-16 14:16:59 <5> suse-admin(10650) [zypp] Exception.cc(log):166 History:
> 2018-08-16 14:16:59 <5> suse-admin(10650) [zypp] Exception.cc(log):166  - Signature verification failed for repomd.xml
> 2018-08-16 14:16:59 <5> suse-admin(10650) [zypp] Exception.cc(log):166 
> 2018-08-16 14:16:59 <5> suse-admin(10650) [zypp] Exception.cc(log):166 repos.cc(refresh_raw_metadata):395 CAUGHT:   [vscode|https://packages.microsoft.com/yumrepos/vscode] Valid metadata not found at specified URL

-    /var/log/salt/minion:

> Warning: File 'repomd.xml' from repository 'vscode' is signed with an unknown key 'EB3E94ADBE1229CF'.
> 
>     Note: Signing data enables the recipient to verify that no modifications occurred after the data
>     were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
>     and in extreme cases even to a system compromise.
> 
>     Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
>     whole repo.
> 
>     Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
>     anymore! You should not continue unless you know it's safe.
> 
> File 'repomd.xml' from repository 'vscode' is signed with an unknown key 'EB3E94ADBE1229CF'. Continue? [yes/no] (no): no
> error]
> 2018-08-16 14:16:59,069 [salt.loaded.int.module.cmdmod:1829][ERROR   ][10630] stderr: Repository 'vscode' is invalid.
> [vscode|https://packages.microsoft.com/yumrepos/vscode] Valid metadata not found at specified URL
> Please check if the URIs defined for this repository are pointing to a valid repository.
> Skipping repository 'vscode' because of the above error.
> Some of the repositories have not been refreshed because of an error.
> 2018-08-16 14:16:59,069 [salt.loaded.int.module.cmdmod:1831][ERROR   ][10630] retcode: 4
> 

4. Visual Studio Code isn't deployable, because rpm doesn't know the gpg key previously imported into zypper.

**Expected Results**: Visual Studio Code is installed. zypper should have an option to also import the gpg key to rpm (like the rpm --import command below).

**Workaround**:  Manually adding gpg-key to rpm via command.
    salt/vscode.sls:
```
#Manually adding key to rpm
'rpm --import https://packages.microsoft.com/keys/microsoft.asc':
  cmd.run
vscode:
  pkgrepo.managed:
    - humanname: "Microsoft Visual Studio Code"
    - mirrorlist: https://packages.microsoft.com/yumrepos/vscode
    - gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    - gpgcheck: 1
    - enabled: 1
    - type: rpm-md
  pkg.installed:
    - name: code
    - fromrepo: vscode
```

Manual Reference: https://en.opensuse.org/Visual_Studio_Code
